In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [46]:
data=pd.read_csv("H://Python//ML with Python//Dataset//house_price.csv")

In [47]:
data

Area  Bedrooms  age   Price
0  2600       4.0   20  550000
1  3000       4.0   15  560000
2  3200       3.0   18  610000
3  3600       5.0   30  590000
4  4000       NaN    8  760000
5  4100       5.0    8  810000
6  4500       6.0   10  830000

In [48]:
import math
median_bedroom=math.floor(data.Bedrooms.median())

In [49]:
median_bedroom

4

In [50]:
data.Bedrooms=data.Bedrooms.fillna(median_bedroom)

In [51]:
data.head(10)

Area  Bedrooms  age   Price
0  2600       4.0   20  550000
1  3000       4.0   15  560000
2  3200       3.0   18  610000
3  3600       5.0   30  590000
4  4000       4.0    8  760000
5  4100       5.0    8  810000
6  4500       6.0   10  830000

In [53]:
reg=linear_model.LinearRegression()
reg.fit(data[['Area','Bedrooms','age']],data.Price)

LinearRegression()

In [54]:
reg.coef_

array([  122.64822746,  8677.94647452, -5983.86607602])

In [57]:
reg.intercept_

289574.1964437616

In [61]:
reg.predict([[4000,4,8]])

C:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([767007.96356887])

Excercise

In [69]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [70]:
df.experience=df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [66]:
df['experience']=df["experience"].astype=int()


In [67]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           0                    6.0                           7      60000
3           0                   10.0                          10      65000
4           0                    9.0                           6      70000
5           0                    7.0                          10      62000
6           0                    NaN                           7      72000
7           0                    7.0                           8      80000

In [75]:
from word2number import w2n

In [76]:
df['experience']=df["experience"].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [77]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [79]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [82]:
regression=linear_model.LinearRegression()
regression.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [84]:
regression.predict([[2,9,6]])

C:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [85]:
regression.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [86]:
regression.intercept_

14992.65144669314

In [87]:
regression.predict([[12,10,10]])

C:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [91]:
df.to_csv('housePrice_csv')